//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class lead
    {
        public int leadId { get; set; }
        public Nullable<int> CustId { get; set; }
        public string Description { get; set; }
        public Nullable<int> PlaingFor { get; set; }
        public Nullable<System.DateTime> PlaningOn { get; set; }
        public string NoOfPersons { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> RatingId { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> statusId { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual Tour_Mst Tour_Mst { get; set; }
    }
}
