//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class stringMap
    {
        public int Id { get; set; }
        public string optionType { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> DisplayValue { get; set; }
    }
}
